server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: "http://bank-eureka-server:8761/eureka/"

spring:
  r2dbc:
    url: r2dbc:postgresql://bank_postgres_user:5432
    username: iamfly
    password: iamfly